### ISSUE TITLE
enchant error

### ISSUE THREAD

**Issue by bipedd** [ztowne13/Specialized-Crates#340]
I have been trying to add looting 3 to my sword in my crate but it won't work, it has 4 enchants already, the enchants are: Unbreaking 3, Sharpness 10, sweeping edge 3 and mending, I want to add looting 3 to this but it always says it doesnt exist when I type LOOTING;3 please help

**Comment by slvlr** [comment]
This issue should be fixed now in 2.13.0 Update.
If it doesn't work, you should try adding LOOT_BONUS_MOBS;3 for swords.
