### ISSUE TITLE
Heads Database compatibility issue.

### ISSUE THREAD

**Issue by 00Hrtz** [ztowne13/Specialized-Crates#342]
You can dupe crates when you assign a custom head from heads database to a Crate, you can then go and buy the custom head from heads database and place it and it's a crate, not a normal custom head.

**Comment by slvlr** [comment]
This isn't exactly a bug. It's happening because you have set the crate item to match everything on that head. You can rename the head of that you use for the crate and add a lore/NBT to it. 
Then in crate "essentials" update the crate item *Everything* .

That stops the issue you are having.

**Comment by 00Hrtz** [comment]
> 
> 
> This isn't exactly a bug. It's happening because you have set the crate item to match everything on that head. You can rename the head of that you use for the crate and add a lore/NBT to it.
> Then in crate "essentials" update the crate item _Everything_ .
> 
> That stops the issue you are having.

OK thanks, i renamed it and it seems to have solved this issue, as there was no information on this anywhere. At least now users have the solution to find here. 

Specialized Crates has been lacking a Wiki for a long time which does the plugin injustice because it's one of the best if not the best crate plugin.
